### PR TITLE
Fix/ci and lint

### PR DESCRIPTION
**Pull request by hcfw007**
swc dependency explaination: https://github.com/swc-project/swc/issues/7203

### CODE REVIEW

**Comment by hcfw007** [comment]
@huan Please checkout this PR that fixes lint and dependency issue. So that we can continue working on new features.

**Review by huan — APPROVED** [review]
LGTM

Thank you very much for cleaning the PR and decoupling them so we can do a better code review in the other one!

**Comment by huan** [comment]
About the swc dependency: can we create another issue in our repo so that we can track it?

Thanks!

**Comment by huan** [comment]
Thanks!

It would be great if we could file an issue for tracking this problem to make it more apparent to the community.

**Pull request merged**
